version: '3'
services:
  api:
    build: ./
    restart: always
    depends_on:
      - "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST=postgres
    networks:
      default:

  nginx:
    image: nginx:alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
      - "443:443"
    restart:
      always

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST=postgres
    networks:
      default:
