version: '3'
services:
  api:
    build: ./
    restart: always
    depends_on:
      - "postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST=postgres
    ports:
      - "8080:80"
    networks:
      default:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST=postgres
    networks:
      default:
